//Events constants that can't be touched.
export enum StatusConstants {
  SUCCESS_BASE = 200,
  OK = SUCCESS_BASE,

  REDIRECTION_MESSAGE_BASE = 300,

  CLIENT_ERROR_BASE = 400,
  BAD_REQUEST = CLIENT_ERROR_BASE,
  INVALID_EMAIL = CLIENT_ERROR_BASE + 2,
  RESOURCE_NOT_FOUND = CLIENT_ERROR_BASE + 4,

  SERVER_ERROR_BASE = 500,
  UNKNOWN_SERVER_ERROR = SERVER_ERROR_BASE,
  EMAIL_SEND_FAIL = SERVER_ERROR_BASE + 1,
  DB_SAVE_ERROR = SERVER_ERROR_BASE + 2,
  NETWORK_ERROR = SERVER_ERROR_BASE + 3,
}
