runtime: nodejs16

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

#runtime: nodejs

# env: flex

# manual_scaling:
#   instances: 1
# resources:
#   cpu: .5
#   memory_gb: 0.90
#   disk_size_gb: 0.5